import "./globals.css";
import type { Metadata } from "next";
import { Inter, Josefin_Sans } from "next/font/google";
import { Provider } from "react-redux";
import Header from "@/shared/Header";
import Footer from "@/shared/Footer";
import ReactProvider from "../../Redux/ReactProvider";
import { Toaster } from "react-hot-toast";

const josefin = Josefin_Sans({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <ReactProvider>
          <Header />
          <Toaster />
          {children}
          <Footer />
        </ReactProvider>
      </body>
    </html>
  );
}
